pipeline:
  test:
    image: ruby:2.3
    commands:
      - bundle install --path=bundler
      - rspec spec/

  docker:
    image: plugins/docker:latest
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    repo: jakolehm/todo-example
    tag: latest
    file: Dockerfile
    when:
      branch: master
      matrix:
        MONGO_VERSION: 3.2

  kontena:
    image: kontena/cli:latest
    environment:
      - SSL_IGNORE_ERRORS=true
    commands:
      - kontena app deploy -f kontena-cluster.yml app
    when:
      branch: master
      matrix:
        MONGO_VERSION: 3.2

services:
  database:
    image: mongo:${MONGO_VERSION}

matrix:
  MONGO_VERSION:
    - 3.2
    - 3.0
