pipeline:
  test:
    image: ruby:2.3
    commands:
      - bundle install --path=bundler
      - rspec spec/

  docker_test:
    image: plugins/docker:latest
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    repo: jakolehm/todo-example
    tag: git-${DRONE_COMMIT}
    file: Dockerfile
    when:
      branch: do-nyc

  deploy_test:
    image: kontena/cli:1.3.4
    environment:
      - INSTANCES=2
      - DRONE_TAG=git-${DRONE_COMMIT}
      - VIRTUAL_HOST=do-nyc-todos.kontena.io
    commands:
      - kontena stack upgrade todo-test
    when:
      branch: do-nyc

services:
  database:
    image: mongo:3.2