pipeline:
  test:
    image: ruby:2.3
    environment:
      - MONGODB_URI=mongodb://mongo:27017/todo_test
    commands:
      - bundle install --path=bundler
      - rspec spec/

  docker_test:
    image: plugins/docker:latest
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    repo: index.docker.io/jakolehm/todo-example
    tag: git-${DRONE_COMMIT}
    file: Dockerfile
    secrets: [ docker_username, docker_password ]
    when:
      branch: do-nyc

  deploy_test:
    image: kontena/cli:1.3.4
    environment:
      - INSTANCES=2
      - DRONE_TAG=git-${DRONE_COMMIT}
      - VIRTUAL_HOST=do-nyc-todos.kontena.io
    commands:
      - kontena stack install --name todo-test kontena.yml || kontena stack upgrade todo-test kontena.yml
    secrets:
      - source: kontena_uri
        target: KONTENA_URL
      - source: kontena_grid
        target: KONTENA_GRID
      - source: kontena_token
        target: KONTENA_TOKEN
    when:
      branch: do-nyc

services:
  mongo:
    image: mongo:3.2