pipeline:
  test:
    image: ruby:2.3
    commands:
      - bundle install --path=bundler
      - rspec spec/

  docker:
    image: plugins/docker:latest
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    repo: jakolehm/todo-example
    tag: latest
    file: Dockerfile
    when:
      branch: master

  kontena:
    image: kontena/cli:latest
    environment:
      - SSL_IGNORE_ERRORS=true
    commands:
      - app deploy -f kontena-cluster.yml app
    when:
      branch: master

services:
  database:
    image: mongo:3.2
