version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/todo_test
    links:
      - mongodb:mongodb
  mongodb:
    image: mongo:3.2
