stack: jakolehm/todo
description: Simple todo app
version: 0.1.0
services:
  app:
    image: quay.io/jakolehm/todo-example:latest
    build: 
      context: .
    environment:
      - MONGODB_URI=mongodb://mongodb.${GRID}.kontena.local/todo_production
