stack: jakolehm/todo
description: Simple todo app
version: 0.1.0
services:
  lb:
    image: kontena/lb:latest
    ports:
      - "80:80"
    deploy:
      strategy: daemon
  app:
    image: quay.io/jakolehm/todo-example:latest
    build: 
      context: .
    command: bundle exec puma -p 9292 -e production
    secrets:
      - secret: TODO_MONGODB_URI
        name: MONGODB_URI
        type: env
    links:
      - lb
    environment:
      - KONTENA_LB_INTERNAL_PORT=9292