version: '2'
services:
  mongodb:
    image: mongo:3.2
    instances: 3
    stateful: true
    command: --replSet kontena --smallfiles
    hooks:
      post_start:
        - cmd: sleep 10
          name: sleep
          instances: 3
          oneshot: true
        - cmd: mongo --eval "printjson(rs.initiate());"
          name: rs_initiate
          instances: 3
          oneshot: true
        - cmd: mongo --eval "printjson(rs.add('%{project}-mongodb-1'))"
          name: rs_add2
          instances: 3
          oneshot: true
        - cmd: mongo --eval "printjson(rs.add('%{project}-mongodb-2'))"
          name: rs_add3
          instances: 3
          oneshot: true

  app:
    image: jakolehm/todo-example:latest
    links:
      - mongodb
    external_links:
      - loadbalancer
    environment:
      - MONGODB_URI=mongodb://%{project}-mongodb-1:27017,%{project}-mongodb-2:27017,%{project}-mongodb-3:27017/todo_production
      - KONTENA_LB_VIRTUAL_PATH=/
      - KONTENA_LB_INTERNAL_PORT=9292
    deploy:
      wait_for_port: 9292
    command: bundle exec puma -p 9292 -e production
