stack: jakolehm/todo
description: Amazing todo app
version: 0.1.0
variables:
  virtual_host:
    type: string
    from:
      env: VIRTUAL_HOST
      prompt: Virtual host
  instances:
    type: integer
    default: 3
    from:
      env: INSTANCES
      prompt: Number of instances
  image_tag:
    type: string
    default: latest
    from: 
      env: DRONE_TAG
services:
  app:
    image: jakolehm/todo-example:{{ image_tag }}
    instances: {{ instances }}
    build: 
      context: .
    command: bundle exec puma -p 9292 -e production
    deploy:
      wait_for_port: 9292
    environment:
      - MONGODB_URI=mongodb://peer-1.mongo.${GRID}.kontena.local:27017,peer-2.mongo.${GRID}.kontena.local:27017,peer-3.mongo.${GRID}.kontena.local:27017/todo_production
      - KONTENA_LB_INTERNAL_PORT=9292
      - KONTENA_LB_VIRTUAL_HOSTS={{ virtual_host }}
    links:
      - ingress-lb/lb