stack: jakolehm/todo
description: Amazing todo app
version: 0.1.0
variables:
  image_tag:
    type: string
    default: latest
    from: 
      env: DRONE_TAG 
services:
  app:
    image: jakolehm/todo-example:{{ image_tag }}
    build: 
      context: .
    command: bundle exec puma -p 9292 -e production
    environment:
      - MONGODB_URI=mongodb://peer-1.mongo.${GRID}.kontena.local:27017,peer-2.mongo.${GRID}.kontena.local:27017,peer-3.mongo.${GRID}.kontena.local:27017
      - KONTENA_LB_INTERNAL_PORT=9292
    links:
      - ingress-lb/lb