stack: jakolehm/todo
description: Amazing todo app
version: 0.1.0
variables:
  todo_mongo_password:
    type: string
    from:
      vault: TODO_MONGO_PASSWORD
      random_string: 14
    to:
      vault: TODO_MONGO_PASSWORD
services:
  app:
    image: quay.io/jakolehm/todo-example:latest
    build: 
      context: .
    command: bundle exec puma -p 9292 -e production
    secrets:
      - secret: TODO_MONGO_PASSWORD
        name: MONGODB_PASSWORD
        type: env
    environment:
      - MONGODB_USERNAME=admin
      - MONGODB_DATABASE=todo_production
      - MONGODB_HOSTS=peer-1.mongo.${GRID}.kontena.local,peer-2.mongo.${GRID}.kontena.local,peer-3.mongo.${GRID}.kontena.local
      - KONTENA_LB_INTERNAL_PORT=9292
    links:
      - http-ingress/lb