test:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || 'mongodb://localhost:27017/todo_test' %>
development:
  clients:
    default:
      database: todo_development
      hosts:
        - localhost:27017
production:
  clients:
    default:
      username: <%= ENV['MONGODB_USERNAME'] || 'admin' %>
      password: "<%= ENV['MONGODB_PASSWORD'] %>"
      database: <%= ENV['MONGODB_DATABASE'] || 'todo_production' %>
      hosts: 
        <% ENV['MONGODB_HOSTS'].split(',').each do |host| %>
        - <%= host %>:27017
        <% end %>
