stack: jakolehm/mongo
expose: peer
version: 0.2.0
description: MongoDB 3.4 replica set (3 members)
services:
  peer:
    image: mongo:3.4
    stateful: true
    instances: 3
    command: --replSet kontena
    health_check:
      protocol: tcp
      port: 27017
    hooks:
      post_start:
        - cmd: sleep 10
          name: sleep
          instances: 3
          oneshot: true
        - cmd: mongo --eval "printjson(rs.initiate());" admin
          name: rs_initiate
          instances: 3
          oneshot: true
        - cmd: mongo --eval "printjson(rs.add('peer-1.${STACK}.${GRID}.kontena.local'))" admin
          name: rs_add2
          instances: 3
          oneshot: true
        - cmd: mongo --eval "printjson(rs.add('peer-2.${STACK}.${GRID}.kontena.local'))" admin
          name: rs_add3
          instances: 3
          oneshot: true
